// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VNP6i_apKVq8WnvIBncU2fQtvwCdXj8',
    appId: '1:273299988498:web:600c9410bb38367e64b8cb',
    messagingSenderId: '273299988498',
    projectId: 'chat-me-820cb',
    authDomain: 'chat-me-820cb.firebaseapp.com',
    storageBucket: 'chat-me-820cb.appspot.com',
    measurementId: 'G-N0QFJ5C2K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDc5ijZ_PwT9um121OGNjeoST1FOQVoSc',
    appId: '1:273299988498:android:9aa8d5f43a3d115164b8cb',
    messagingSenderId: '273299988498',
    projectId: 'chat-me-820cb',
    storageBucket: 'chat-me-820cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sB0axPQgzRDg1Albvo6H7F1xecSqY6A',
    appId: '1:273299988498:ios:f28acba4f74289b864b8cb',
    messagingSenderId: '273299988498',
    projectId: 'chat-me-820cb',
    storageBucket: 'chat-me-820cb.appspot.com',
    iosClientId: '273299988498-t05b12bu4mhb3gcscq21ok54tphq6urj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8sB0axPQgzRDg1Albvo6H7F1xecSqY6A',
    appId: '1:273299988498:ios:3ead42217bdc7fc664b8cb',
    messagingSenderId: '273299988498',
    projectId: 'chat-me-820cb',
    storageBucket: 'chat-me-820cb.appspot.com',
    iosClientId: '273299988498-c73ovd3j4elmsd13scueckjivch4cjd0.apps.googleusercontent.com',
    iosBundleId: 'com.chatme.app',
  );
}
